CREATE DATABASE SP_MedGroup;
GO

USE SP_MedGroup;
GO

CREATE TABLE tipoUsuario(
 idTipo TINYINT PRIMARY KEY IDENTITY,
 nomeTipo VARCHAR(100) NOT NULL UNIQUE
);
GO

CREATE TABLE usuario(
 idUsuario INT PRIMARY KEY IDENTITY, 
 idTipo TINYINT FOREIGN KEY REFERENCES tipoUsuario(idTipo),
 nome VARCHAR(150) NOT NULL,
 email VARCHAR(256) NOT NULL UNIQUE,
 senha VARCHAR(25) NOT NULL
);
GO

CREATE TABLE especializacao(
 idEspecializacao TINYINT PRIMARY KEY IDENTITY,
 nomeEspecializacao VARCHAR(100) NOT NULL UNIQUE
);
GO


CREATE TABLE instituicao (
 idInstituicao SMALLINT PRIMARY KEY IDENTITY,
 nomeFantasia VARCHAR(200) NOT NULL,
 cnpj VARCHAR(20) NOT NULL UNIQUE,
 razaoSocial VARCHAR(200) NOT NULL UNIQUE,
 endereco VARCHAR(200) NOT NULL UNIQUE
);
GO

CREATE TABLE paciente(
 idPaciente INT PRIMARY KEY IDENTITY,
 idUsuario INT FOREIGN KEY REFERENCES usuario(idUsuario),
 dataNascimento DATE NOT NULL,
 telefone VARCHAR(20) UNIQUE,
 rg VARCHAR(15) NOT NULL UNIQUE,
 cpf VARCHAR(15) NOT NULL UNIQUE,
 endereco VARCHAR NOT NULL
);
GO
